server:
  port: 9007
       
spring:
  application:
    name: UMS-DOCUMENT-SERVICE
    
  cloud:
    config:
      uri: http://localhost:9004
  
  profiles:
    active: dev2
    
  jpa:
     database-platform: org.hibernate.dialect.PostgreSQLDialect
     hibernate:
       ddl-auto: none
     properties:
       hibernate:
         temp:
            use_jdbc_metadata_defaults: false
ums:
  tenant:
      client:
         service-name: UMS-DOCUMENT-SERVICE
                  
management:
  endpoints:
     web:
       exposure:
           include: filters, health, info, metrics