server:
  port: 9006

spring:
  application:
    name: UMS-DOCUMENT-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://129.158.243.246:5432/umsdocumentdb
    username: postgres
    password: manager
  devtools:
    restart:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
#ikcontech.com
app:
  clientId: ${AZURE_CLIENT_ID}
  clientSecret: ${AZURE_CLIENT_SECRET}
  tenantId: ${AZURE_TENANT_ID}


azure:
  bot:
    directline:
      secret: ${AZURE_DIRECTLINE_SECRET}